import binascii
import csv
import os
from pathlib import Path
import struct
import sys
import tempfile
import time
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "desktop"))
from protocol import HEADER, StreamParser
from wave_viewer import SerialReader, demo_frame, write_csv


def packet(wave=((100, 200), (300, 300)), flags=1, version=1):
    payload = HEADER.pack(version, flags, 1, 0, 42, 1234, 2048, 1550,
                          len(wave), 10, 216, 3100)
    payload += b"".join(struct.pack("<HH", *pair) for pair in wave)
    body = struct.pack("<H", len(payload)) + payload
    return b"ADCW" + body + struct.pack("<H", binascii.crc_hqx(body, 0xffff))


class ProtocolTests(unittest.TestCase):
    def test_fragmented_logs_and_concatenated_frames(self):
        data = b"ESP-ROM boot\r\nADC: 4000 samples/s\n" + packet() + packet(wave=())
        for chunk_size in (1, 3, 7, 32, 4096):
            parser = StreamParser()
            frames = []
            for i in range(0, len(data), chunk_size):
                frames.extend(parser.feed(data[i:i + chunk_size]))
            self.assertEqual(len(frames), 2)
            self.assertEqual(frames[0].wave, ((100, 200), (300, 300)))
            self.assertEqual(frames[1].wave, ())
            self.assertTrue(frames[0].usable)
            self.assertEqual(parser.errors, 0)

    def test_corruption_and_truncation_recover(self):
        damaged = bytearray(packet())
        damaged[16] ^= 0x80
        parser = StreamParser()
        stream = (b"ADCW\xff\xff" + damaged + packet()[:-5] +
                  packet(version=2) + packet(wave=((200, 100),)) + packet())
        frames = parser.feed(stream)
        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].sequence, 42)
        self.assertGreaterEqual(parser.errors, 4)

    def test_bound_buffer_and_stale(self):
        parser = StreamParser()
        parser.feed(b"x" * 100000)
        self.assertLessEqual(len(parser.buffer), 3)
        self.assertFalse(parser.feed(packet(flags=5))[0].usable)
        self.assertFalse(parser.feed(packet(flags=0))[0].usable)

    def test_firmware_fixture(self):
        fixture = os.environ.get("ADCW_FIXTURE")
        if not fixture:
            self.skipTest("Set ADCW_FIXTURE to the binary generated by wave_protocol_test")
        parser = StreamParser()
        frames = parser.feed(Path(fixture).read_bytes())
        self.assertEqual(len(frames), 1)
        frame = frames[0]
        self.assertEqual(frame.sequence, 0x12345678)
        self.assertEqual(frame.timestamp_ms, 0xfffffff0)
        self.assertEqual(frame.flags, 3)
        self.assertEqual(frame.raw_mean, 2048)
        self.assertEqual(frame.millivolts, 1550)
        self.assertEqual((frame.columns, frame.column_ms, frame.max_mv), (216, 10, 3100))
        self.assertEqual(frame.wave, tuple((1000 + i, 1100 + i) for i in range(216)))

    def test_csv_snapshot(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "wave.csv"
            write_csv(path, demo_frame(3))
            with path.open(encoding="utf-8-sig", newline="") as source:
                rows = list(csv.DictReader(source))
            self.assertEqual(len(rows), 216)
            self.assertAlmostEqual(float(rows[0]["relative_bucket_start_s"]), -2.16)
            self.assertEqual(float(rows[-1]["relative_bucket_end_s"]), 0)

    def test_reader_disconnect_and_latest_only(self):
        class Port:
            in_waiting = 4096
            closed = False
            reads = 0

            def read(self, _size):
                self.reads += 1
                if self.reads == 1:
                    return packet() * 100
                raise OSError("device removed")

            def close(self):
                self.closed = True

        port = Port()
        reader = SerialReader(port)
        reader.start()
        reader.join(timeout=2)
        self.assertFalse(reader.is_alive())
        self.assertTrue(port.closed)
        self.assertEqual(reader.count, 100)
        self.assertEqual(reader.latest.qsize(), 1)
        self.assertIn("device removed", reader.error)

    @unittest.skipUnless(os.environ.get("ADCW_GUI_TEST"), "Optional Tk GUI smoke test")
    def test_gui_demo_pause_and_stale(self):
        import tkinter as tk
        from wave_viewer import WaveViewer
        root = tk.Tk()
        root.withdraw()
        app = WaveViewer(root, demo=True)
        try:
            root.update_idletasks()
            app.canvas.configure(width=900, height=400)
            # Withdrawn widgets do not receive normal geometry allocation.
            app.canvas.winfo_width = lambda: 900
            app.canvas.winfo_height = lambda: 400
            app.latest = demo_frame(3)
            app.displayed = app.latest
            app.last_received = time.monotonic()
            app.draw()
            self.assertIn("V", app.voltage.get())
            self.assertGreater(len(app.canvas.find_all()), 216)
            app.toggle_pause()
            frozen = app.displayed
            app.latest = demo_frame(4)
            self.assertIs(app.displayed, frozen)
            app.toggle_pause()
            self.assertIs(app.displayed, app.latest)
            app.last_received -= 2
            app.draw()
            self.assertEqual(app.voltage.get(), "--.--- V")
            from unittest.mock import patch
            with patch("wave_viewer.messagebox.showinfo") as info, patch("wave_viewer.filedialog.asksaveasfilename") as save:
                app.export()
                info.assert_called_once()
                save.assert_not_called()
            app.disconnect()
            app.reset_view()
            self.assertIsNone(app.displayed)
        finally:
            app.close()


if __name__ == "__main__":
    unittest.main()
